/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.olmo.Principal;

/**
 *
 * @author OLMO
 */
public class Registro extends javax.swing.JDialog {

    /**
     * Creates new form Registro
     */
    
    Principal principal;
    public Registro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        principal=(Principal)parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPrimerPlato = new javax.swing.JLabel();
        labelSegundoPlato = new javax.swing.JLabel();
        labelPostre = new javax.swing.JLabel();
        buttonAnadir = new javax.swing.JButton();
        comboPostre = new javax.swing.JComboBox<>();
        comboPrimero = new javax.swing.JComboBox<>();
        comboSegundo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelPrimerPlato.setText("Primer plato");

        labelSegundoPlato.setText("Segundo plato");

        labelPostre.setText("Postre");

        buttonAnadir.setText("Añadir menu ");
        buttonAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnadirActionPerformed(evt);
            }
        });

        comboPostre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarta De Queso", "Tocinillo de Cielo ", "Flan", "Yogurt Natural ", " " }));
        comboPostre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPostreActionPerformed(evt);
            }
        });

        comboPrimero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ensalada Mixta", "Ensalada De Cecina", "Fabada", "Pote Asturiano ", " " }));
        comboPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPrimeroActionPerformed(evt);
            }
        });

        comboSegundo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cachopo", "Dorada a la Espalda", "Secreto ibérico", "Bacalao", " " }));
        comboSegundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSegundoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSegundoPlato)
                            .addComponent(labelPrimerPlato)
                            .addComponent(labelPostre))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboSegundo, 0, 194, Short.MAX_VALUE)
                            .addComponent(comboPostre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(buttonAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 55, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(179, Short.MAX_VALUE)
                    .addComponent(comboPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(53, 53, 53)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(labelPrimerPlato)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSegundoPlato)
                    .addComponent(comboSegundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPostre)
                    .addComponent(comboPostre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(buttonAnadir)
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(comboPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(212, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnadirActionPerformed
          Menu menu = new Menu((String)comboPrimero.getSelectedItem(),
                  (String)comboSegundo.getSelectedItem(),
                  (String)comboPostre.getSelectedItem());
              principal.anadirMenu(menu);
        
        this.dispose();
    }//GEN-LAST:event_buttonAnadirActionPerformed

    private void comboPostreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPostreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPostreActionPerformed

    private void comboPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPrimeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPrimeroActionPerformed

    private void comboSegundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSegundoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSegundoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Registro dialog = new Registro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAnadir;
    private javax.swing.JComboBox<String> comboPostre;
    private javax.swing.JComboBox<String> comboPrimero;
    private javax.swing.JComboBox<String> comboSegundo;
    private javax.swing.JLabel labelPostre;
    private javax.swing.JLabel labelPrimerPlato;
    private javax.swing.JLabel labelSegundoPlato;
    // End of variables declaration//GEN-END:variables
}
